ALMinium:
  restart: always
  image: ayapapa/docker-alminium:0.7
  ports:
    - "10080:80"
  environment:
    - ALM_HOSTNAME=localhost
    - ALM_RELATIVE_URL_ROOT=
  volumes:
    - /home/alminium/files:/opt/alminium/files
    - /home/alminium/db:/var/lib/mysql
    - /home/alminium/repo:/var/opt/alminium
