ALMinium:
  restart: always
  image: ayapapa/docker-alminium:3.2.0c

  ports:
    - "10080:80"

  environment:
    - ALM_HOSTNAME=www.example.com
    - ALM_RELATIVE_URL_ROOT=
    - ALM_ENABLE_AUTO_BACKUP=y
    - ALM_BACKUP_MINUTE=0
    - ALM_BACKUP_HOUR=3
    - ALM_BACKUP_DAY=*/2
    - ALM_BACKUP_EXPIRY=14

    - SMTP_ENABLED=false
    - SMTP_ENALBLE_STARTTLS_AUTO=true
    - SMTP_ADDRESS=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_DOMAIN=smtp.gmail.com
    - SMTP_AUTHENTICATION=:login
    - SMTP_USER_NAME=example@gmail.com
    - SMTP_PASS=****

  volumes:
    - /home/alminium/files:/opt/alminium/files
    - /home/alminium/db:/var/lib/mysql
    - /home/alminium/repo:/var/opt/alminium
