ALMinium:
  restart: always
  image: ayapapa/docker-alminium:3.3.1f

  ports:
    - "10080:80"
    - "10443:443"

  environment:
    - ALM_HOSTNAME=www.example.com
    - ALM_RELATIVE_URL_ROOT=
    - ALM_ENABLE_AUTO_BACKUP=y
    - ALM_BACKUP_MINUTE=0
    - ALM_BACKUP_HOUR=3
    - ALM_BACKUP_DAY=*/2
    - ALM_BACKUP_EXPIRY=14
    - ALM_ENABLE_SSL=N
    - ALM_PORT=10080

    - SMTP_ENABLED=false
    - SMTP_ENALBLE_STARTTLS_AUTO=true
    - SMTP_ADDRESS=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_DOMAIN=smtp.gmail.com
    - SMTP_AUTHENTICATION=:login
    - SMTP_USER_NAME=example@gmail.com
    - SMTP_PASS=****

  volumes:
    - /home/alminium/files:/opt/alminium/files
    - /home/alminium/db:/var/lib/mysql
    - /home/alminium/repo:/var/opt/alminium
    - /home/alminium/log:/var/log/alminium
    - /home/alminium/backup:/var/opt/alminium-backup
    - ./update.sh:/home/alm/update.sh
