version: '2'

services:
  mysql:
    restart: always

    image: sameersbn/mysql

    volumes:
    - /home/alminium/db:/var/lib/mysql
    - /home/alminium/log:/var/log

    environment:
    - MYSQL_ROOT_PASSWORD= 
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - DB_NAME=alminium
    - DB_USER=alminium
    - DB_PASS=alminium

  alminium:
    restart: always

    image: ayapapa/docker-alminium:3.3.2

    ports:
    - "10080:80"
    - "10443:443"

    depends_on:
    - mysql

    links:
    - mysql:db

    environment:
    - ALM_HOSTNAME=192.168.11.20
    - ALM_RELATIVE_URL_ROOT=
    - ALM_ENABLE_AUTO_BACKUP=y
    - ALM_BACKUP_MINUTE=0
    - ALM_BACKUP_HOUR=3
    - ALM_BACKUP_DAY=*/2
    - ALM_BACKUP_EXPIRY=14
    - ALM_ENABLE_SSL=N
    - ALM_PORT=10080

    - SMTP_ENABLED=false
    - SMTP_ENALBLE_STARTTLS_AUTO=true
    - SMTP_ADDRESS=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_DOMAIN=smtp.gmail.com
    - SMTP_AUTHENTICATION=:login
    - SMTP_USER_NAME=example@gmail.com
    - SMTP_PASS=****

    volumes:
    - /home/alminium/files:/opt/alminium/files
    - /home/alminium/db:/var/lib/mysql
    - /home/alminium/repo:/var/opt/alminium
    - /home/alminium/log:/var/log/alminium
    - ./update.sh:/home/alm/update.sh
