#!/bin/bash

ETH0=eth0
if [ -f /etc/redhat-release ]; then
  CHK= `egrep "CentOS Linux release 7" /etc/redhat-release`
  if [ "$CHK" != "" ]; then
    ETH0=enp0s3
  fi
fi

IP_ADDR="`ip -f inet -o addr show $ETH0 | cut -d\  -f 7 | cut -d/ -f 1`"
cp docker-compose.yml docker-compose.yml.old
sed "s/www.example.com/$IP_ADDR/" docker-compose.yml.old > docker-compose.yml
